; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Common configuration for both boards
[env]
platform = espressif32@7.0.1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv
upload_protocol = esptool
upload_speed = 460800
monitor_rts = 0
monitor_dtr = 0
build_flags = 
  -DARDUINO_USB_CDC_ON_BOOT=1
  -Os
  -DCORE_DEBUG_LEVEL=0
  -DWEIGHMYBRU_BUILD_NUMBER=1
  -DWEIGHMYBRU_COMMIT_HASH=\"dev\"
  -D CONFIG_NIMBLE_CPP_LOG_LEVEL=4 
  -D CONFIG_NIMBLE_CPP_ENABLE_RETURN_CODE_TEXT=1
lib_deps = 
	robtillaart/HX711@^0.6.0
	https://github.com/ESP32Async/AsyncTCP.git ;https://github.com/me-no-dev/ESPAsyncWebServer.git
	https://github.com/ESP32Async/ESPAsyncWebServer.git ;https://github.com/me-no-dev/AsyncTCP.git
	h2zero/NimBLE-Arduino@^2.5.0
	adafruit/Adafruit SSD1306@^2.5.7
	adafruit/Adafruit GFX Library@^1.11.9

; ESP32-S3-DevKitC-1 (SuperMini) Environment
[env:esp32s3-supermini]
board = esp32-s3-devkitc-1
board_upload.flash_size = 4MB
upload_port = COM12
monitor_port = COM12
upload_flags = 
  --chip=esp32s3
  --before=default_reset
  --after=hard_reset
build_flags = 
  ${env.build_flags}
  -DBOARD_HAS_PSRAM
  -DBOARD_SUPERMINI
  -DCONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_80=1
  -DCONFIG_ESP_DEFAULT_CPU_FREQ_MHZ=80

; XIAO ESP32S3 Environment  
[env:esp32s3-xiao]
board = seeed_xiao_esp32s3
board_upload.flash_size = 8MB
upload_flags = 
  --chip=esp32s3
  --before=default_reset
  --after=hard_reset
build_flags = 
  ${env.build_flags}
  -DBOARD_HAS_PSRAM
  -DBOARD_XIAO
  -DCONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_80=1
  -DCONFIG_ESP_DEFAULT_CPU_FREQ_MHZ=80

; XIAO ESP32C6 Environment  
[env:esp32c6-xiao]
platform = https://github.com/pioarduino/platform-espressif32.git#53.03.13
board = seeed_xiao_esp32c6
board_upload.flash_size = 8MB
upload_flags = 
  --chip=esp32c6
  --before=default_reset
  --after=hard_reset
build_flags = 
  ${env.build_flags}
  -DBOARD_XIAOC6
  -DARDUINO_USB_CDC_ON_BOOT=1

  ; C6 should use https://github.com/ESP32Async/AsyncTCP.git and https://github.com/ESP32Async/ESPAsyncWebServer.git