#ifndef VERSION_H
#define VERSION_H

// Manual version control (update these for releases)
#define WEIGHMYBRU_VERSION_MAJOR 2
#define WEIGHMYBRU_VERSION_MINOR 2
#define WEIGHMYBRU_VERSION_PATCH 0
#define WEIGHMYBRU_VERSION_PRERELEASE  // "", "beta", "rc1", etc.

// Automatic build info (filled by build system)
#ifndef WEIGHMYBRU_BUILD_NUMBER
#define WEIGHMYBRU_BUILD_NUMBER 0
#endif

#ifndef WEIGHMYBRU_COMMIT_HASH
#define WEIGHMYBRU_COMMIT_HASH "unknown"
#endif

// Helper macros for string conversion
#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

// Version string construction
#ifdef WEIGHMYBRU_VERSION_PRERELEASE
  #define WEIGHMYBRU_VERSION_STRING TOSTRING(WEIGHMYBRU_VERSION_MAJOR) "." TOSTRING(WEIGHMYBRU_VERSION_MINOR) "." TOSTRING(WEIGHMYBRU_VERSION_PATCH) "-" WEIGHMYBRU_VERSION_PRERELEASE
#else
  #define WEIGHMYBRU_VERSION_STRING TOSTRING(WEIGHMYBRU_VERSION_MAJOR) "." TOSTRING(WEIGHMYBRU_VERSION_MINOR) "." TOSTRING(WEIGHMYBRU_VERSION_PATCH)
#endif

#define WEIGHMYBRU_FULL_VERSION WEIGHMYBRU_VERSION_STRING "+build." TOSTRING(WEIGHMYBRU_BUILD_NUMBER) "." WEIGHMYBRU_COMMIT_HASH
#define WEIGHMYBRU_BUILD_DATE __DATE__
#define WEIGHMYBRU_BUILD_TIME __TIME__

// Board identification
#ifdef BOARD_SUPERMINI
  #define WEIGHMYBRU_BOARD_NAME "ESP32-S3 Supermini"
#elif defined(BOARD_XIAO)
  #define WEIGHMYBRU_BOARD_NAME "XIAO ESP32S3"
#elif defined(BOARD_XIAOC6)
  #define WEIGHMYBRU_BOARD_NAME "XIAO ESP32C6"
#else
  #define WEIGHMYBRU_BOARD_NAME "Unknown ESP32"
#endif

#endif // VERSION_H